# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d39b3c3a16bed86cdad3f98cbf25a7ef6e79757bd471a5cb2c9d0224cbaf9c3a74dc91080910d72431232b63874800ce5001918866b7b8cc123ae0e9656256

test:
  secret_key_base: eaea30d85c1620b59594161fb61a6b8717039c9f4e8d4b61cfbf4eaa7f8673a30ba41adb5ce8256420116c726655949740360eb9d3d3b4f86f1f7754a9d2b628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
